return {
  sheets = {
    ["character_astronaut_board"] = {
      file = "assets/love_sprites/character_astronaut_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "astronaut",
    },
    ["character_astronaut_cheer"] = {
      file = "assets/love_sprites/character_astronaut_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "astronaut",
    },
    ["character_astronaut_idle"] = {
      file = "assets/love_sprites/character_astronaut_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "astronaut",
    },
    ["character_astronaut_walk"] = {
      file = "assets/love_sprites/character_astronaut_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "astronaut",
    },
    ["character_astronaut_wave"] = {
      file = "assets/love_sprites/character_astronaut_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "astronaut",
    },
    ["character_bear_tourist_board"] = {
      file = "assets/love_sprites/character_bear_tourist_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "bear_tourist",
    },
    ["character_bear_tourist_cheer"] = {
      file = "assets/love_sprites/character_bear_tourist_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "bear_tourist",
    },
    ["character_bear_tourist_idle"] = {
      file = "assets/love_sprites/character_bear_tourist_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "bear_tourist",
    },
    ["character_bear_tourist_walk"] = {
      file = "assets/love_sprites/character_bear_tourist_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "bear_tourist",
    },
    ["character_bear_tourist_wave"] = {
      file = "assets/love_sprites/character_bear_tourist_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "bear_tourist",
    },
    ["character_conductor_board"] = {
      file = "assets/love_sprites/character_conductor_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "conductor",
    },
    ["character_conductor_cheer"] = {
      file = "assets/love_sprites/character_conductor_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "conductor",
    },
    ["character_conductor_idle"] = {
      file = "assets/love_sprites/character_conductor_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "conductor",
    },
    ["character_conductor_walk"] = {
      file = "assets/love_sprites/character_conductor_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "conductor",
    },
    ["character_conductor_wave"] = {
      file = "assets/love_sprites/character_conductor_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "conductor",
    },
    ["character_cool_cat_board"] = {
      file = "assets/love_sprites/character_cool_cat_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "cool_cat",
    },
    ["character_cool_cat_cheer"] = {
      file = "assets/love_sprites/character_cool_cat_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "cool_cat",
    },
    ["character_cool_cat_idle"] = {
      file = "assets/love_sprites/character_cool_cat_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "cool_cat",
    },
    ["character_cool_cat_walk"] = {
      file = "assets/love_sprites/character_cool_cat_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "cool_cat",
    },
    ["character_cool_cat_wave"] = {
      file = "assets/love_sprites/character_cool_cat_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "cool_cat",
    },
    ["character_fox_passenger_board"] = {
      file = "assets/love_sprites/character_fox_passenger_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "fox_passenger",
    },
    ["character_fox_passenger_cheer"] = {
      file = "assets/love_sprites/character_fox_passenger_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "fox_passenger",
    },
    ["character_fox_passenger_idle"] = {
      file = "assets/love_sprites/character_fox_passenger_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "fox_passenger",
    },
    ["character_fox_passenger_walk"] = {
      file = "assets/love_sprites/character_fox_passenger_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "fox_passenger",
    },
    ["character_fox_passenger_wave"] = {
      file = "assets/love_sprites/character_fox_passenger_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "fox_passenger",
    },
    ["character_frog_friend_board"] = {
      file = "assets/love_sprites/character_frog_friend_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "frog_friend",
    },
    ["character_frog_friend_cheer"] = {
      file = "assets/love_sprites/character_frog_friend_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "frog_friend",
    },
    ["character_frog_friend_idle"] = {
      file = "assets/love_sprites/character_frog_friend_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "frog_friend",
    },
    ["character_frog_friend_walk"] = {
      file = "assets/love_sprites/character_frog_friend_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "frog_friend",
    },
    ["character_frog_friend_wave"] = {
      file = "assets/love_sprites/character_frog_friend_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "frog_friend",
    },
    ["character_rabbit_passenger_board"] = {
      file = "assets/love_sprites/character_rabbit_passenger_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "rabbit_passenger",
    },
    ["character_rabbit_passenger_cheer"] = {
      file = "assets/love_sprites/character_rabbit_passenger_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "rabbit_passenger",
    },
    ["character_rabbit_passenger_idle"] = {
      file = "assets/love_sprites/character_rabbit_passenger_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "rabbit_passenger",
    },
    ["character_rabbit_passenger_walk"] = {
      file = "assets/love_sprites/character_rabbit_passenger_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "rabbit_passenger",
    },
    ["character_rabbit_passenger_wave"] = {
      file = "assets/love_sprites/character_rabbit_passenger_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "rabbit_passenger",
    },
    ["character_sheep_hiker_board"] = {
      file = "assets/love_sprites/character_sheep_hiker_board.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "sheep_hiker",
    },
    ["character_sheep_hiker_cheer"] = {
      file = "assets/love_sprites/character_sheep_hiker_cheer.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "sheep_hiker",
    },
    ["character_sheep_hiker_idle"] = {
      file = "assets/love_sprites/character_sheep_hiker_idle.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "sheep_hiker",
    },
    ["character_sheep_hiker_walk"] = {
      file = "assets/love_sprites/character_sheep_hiker_walk.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "walk",
      subject = "sheep_hiker",
    },
    ["character_sheep_hiker_wave"] = {
      file = "assets/love_sprites/character_sheep_hiker_wave.png",
      frameWidth = 44,
      frameHeight = 50,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "wave",
      subject = "sheep_hiker",
    },
    ["character_train_dog_board"] = {
      file = "assets/love_sprites/character_train_dog_board.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "board",
      subject = "train_dog",
    },
    ["character_train_dog_cheer"] = {
      file = "assets/love_sprites/character_train_dog_cheer.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "cheer",
      subject = "train_dog",
    },
    ["character_train_dog_duck"] = {
      file = "assets/love_sprites/character_train_dog_duck.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "duck",
      subject = "train_dog",
    },
    ["character_train_dog_hurt"] = {
      file = "assets/love_sprites/character_train_dog_hurt.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "hurt",
      subject = "train_dog",
    },
    ["character_train_dog_idle"] = {
      file = "assets/love_sprites/character_train_dog_idle.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "idle",
      subject = "train_dog",
    },
    ["character_train_dog_jump"] = {
      file = "assets/love_sprites/character_train_dog_jump.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "jump",
      subject = "train_dog",
    },
    ["character_train_dog_land"] = {
      file = "assets/love_sprites/character_train_dog_land.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "land",
      subject = "train_dog",
    },
    ["character_train_dog_move"] = {
      file = "assets/love_sprites/character_train_dog_move.png",
      frameWidth = 92,
      frameHeight = 58,
      frames = 4,
      duration = 0.12,
      category = "character",
      action = "move",
      subject = "train_dog",
    },
    ["collectible_gold_whistle_collect"] = {
      file = "assets/love_sprites/collectible_gold_whistle_collect.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "collect",
      subject = "gold_whistle",
    },
    ["collectible_gold_whistle_idle"] = {
      file = "assets/love_sprites/collectible_gold_whistle_idle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "idle",
      subject = "gold_whistle",
    },
    ["collectible_gold_whistle_sparkle"] = {
      file = "assets/love_sprites/collectible_gold_whistle_sparkle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "sparkle",
      subject = "gold_whistle",
    },
    ["collectible_gold_whistle_spin"] = {
      file = "assets/love_sprites/collectible_gold_whistle_spin.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "spin",
      subject = "gold_whistle",
    },
    ["collectible_rainbow_ticket_collect"] = {
      file = "assets/love_sprites/collectible_rainbow_ticket_collect.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "collect",
      subject = "rainbow_ticket",
    },
    ["collectible_rainbow_ticket_idle"] = {
      file = "assets/love_sprites/collectible_rainbow_ticket_idle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "idle",
      subject = "rainbow_ticket",
    },
    ["collectible_rainbow_ticket_sparkle"] = {
      file = "assets/love_sprites/collectible_rainbow_ticket_sparkle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "sparkle",
      subject = "rainbow_ticket",
    },
    ["collectible_rainbow_ticket_spin"] = {
      file = "assets/love_sprites/collectible_rainbow_ticket_spin.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "spin",
      subject = "rainbow_ticket",
    },
    ["collectible_silver_bone_collect"] = {
      file = "assets/love_sprites/collectible_silver_bone_collect.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "collect",
      subject = "silver_bone",
    },
    ["collectible_silver_bone_idle"] = {
      file = "assets/love_sprites/collectible_silver_bone_idle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "idle",
      subject = "silver_bone",
    },
    ["collectible_silver_bone_sparkle"] = {
      file = "assets/love_sprites/collectible_silver_bone_sparkle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "sparkle",
      subject = "silver_bone",
    },
    ["collectible_silver_bone_spin"] = {
      file = "assets/love_sprites/collectible_silver_bone_spin.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "spin",
      subject = "silver_bone",
    },
    ["collectible_star_coin_collect"] = {
      file = "assets/love_sprites/collectible_star_coin_collect.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "collect",
      subject = "star_coin",
    },
    ["collectible_star_coin_idle"] = {
      file = "assets/love_sprites/collectible_star_coin_idle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "idle",
      subject = "star_coin",
    },
    ["collectible_star_coin_sparkle"] = {
      file = "assets/love_sprites/collectible_star_coin_sparkle.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "sparkle",
      subject = "star_coin",
    },
    ["collectible_star_coin_spin"] = {
      file = "assets/love_sprites/collectible_star_coin_spin.png",
      frameWidth = 30,
      frameHeight = 28,
      frames = 4,
      duration = 0.12,
      category = "collectible",
      action = "spin",
      subject = "star_coin",
    },
    ["environment_arctic_arrival_flash"] = {
      file = "assets/love_sprites/environment_arctic_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "arctic",
    },
    ["environment_arctic_cloud_drift"] = {
      file = "assets/love_sprites/environment_arctic_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "arctic",
    },
    ["environment_arctic_danger_shake"] = {
      file = "assets/love_sprites/environment_arctic_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "arctic",
    },
    ["environment_arctic_full_scroll"] = {
      file = "assets/love_sprites/environment_arctic_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "arctic",
    },
    ["environment_arctic_parallax_far"] = {
      file = "assets/love_sprites/environment_arctic_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "arctic",
    },
    ["environment_arctic_parallax_mid"] = {
      file = "assets/love_sprites/environment_arctic_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "arctic",
    },
    ["environment_arctic_parallax_near"] = {
      file = "assets/love_sprites/environment_arctic_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "arctic",
    },
    ["environment_arctic_rail_scroll"] = {
      file = "assets/love_sprites/environment_arctic_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "arctic",
    },
    ["environment_city_arrival_flash"] = {
      file = "assets/love_sprites/environment_city_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "city",
    },
    ["environment_city_cloud_drift"] = {
      file = "assets/love_sprites/environment_city_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "city",
    },
    ["environment_city_danger_shake"] = {
      file = "assets/love_sprites/environment_city_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "city",
    },
    ["environment_city_full_scroll"] = {
      file = "assets/love_sprites/environment_city_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "city",
    },
    ["environment_city_parallax_far"] = {
      file = "assets/love_sprites/environment_city_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "city",
    },
    ["environment_city_parallax_mid"] = {
      file = "assets/love_sprites/environment_city_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "city",
    },
    ["environment_city_parallax_near"] = {
      file = "assets/love_sprites/environment_city_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "city",
    },
    ["environment_city_rail_scroll"] = {
      file = "assets/love_sprites/environment_city_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "city",
    },
    ["environment_desert_arrival_flash"] = {
      file = "assets/love_sprites/environment_desert_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "desert",
    },
    ["environment_desert_cloud_drift"] = {
      file = "assets/love_sprites/environment_desert_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "desert",
    },
    ["environment_desert_danger_shake"] = {
      file = "assets/love_sprites/environment_desert_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "desert",
    },
    ["environment_desert_full_scroll"] = {
      file = "assets/love_sprites/environment_desert_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "desert",
    },
    ["environment_desert_parallax_far"] = {
      file = "assets/love_sprites/environment_desert_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "desert",
    },
    ["environment_desert_parallax_mid"] = {
      file = "assets/love_sprites/environment_desert_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "desert",
    },
    ["environment_desert_parallax_near"] = {
      file = "assets/love_sprites/environment_desert_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "desert",
    },
    ["environment_desert_rail_scroll"] = {
      file = "assets/love_sprites/environment_desert_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "desert",
    },
    ["environment_forest_arrival_flash"] = {
      file = "assets/love_sprites/environment_forest_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "forest",
    },
    ["environment_forest_cloud_drift"] = {
      file = "assets/love_sprites/environment_forest_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "forest",
    },
    ["environment_forest_danger_shake"] = {
      file = "assets/love_sprites/environment_forest_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "forest",
    },
    ["environment_forest_full_scroll"] = {
      file = "assets/love_sprites/environment_forest_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "forest",
    },
    ["environment_forest_parallax_far"] = {
      file = "assets/love_sprites/environment_forest_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "forest",
    },
    ["environment_forest_parallax_mid"] = {
      file = "assets/love_sprites/environment_forest_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "forest",
    },
    ["environment_forest_parallax_near"] = {
      file = "assets/love_sprites/environment_forest_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "forest",
    },
    ["environment_forest_rail_scroll"] = {
      file = "assets/love_sprites/environment_forest_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "forest",
    },
    ["environment_moon_arrival_flash"] = {
      file = "assets/love_sprites/environment_moon_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "moon",
    },
    ["environment_moon_cloud_drift"] = {
      file = "assets/love_sprites/environment_moon_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "moon",
    },
    ["environment_moon_danger_shake"] = {
      file = "assets/love_sprites/environment_moon_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "moon",
    },
    ["environment_moon_full_scroll"] = {
      file = "assets/love_sprites/environment_moon_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "moon",
    },
    ["environment_moon_parallax_far"] = {
      file = "assets/love_sprites/environment_moon_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "moon",
    },
    ["environment_moon_parallax_mid"] = {
      file = "assets/love_sprites/environment_moon_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "moon",
    },
    ["environment_moon_parallax_near"] = {
      file = "assets/love_sprites/environment_moon_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "moon",
    },
    ["environment_moon_rail_scroll"] = {
      file = "assets/love_sprites/environment_moon_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "moon",
    },
    ["environment_mountains_arrival_flash"] = {
      file = "assets/love_sprites/environment_mountains_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "mountains",
    },
    ["environment_mountains_cloud_drift"] = {
      file = "assets/love_sprites/environment_mountains_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "mountains",
    },
    ["environment_mountains_danger_shake"] = {
      file = "assets/love_sprites/environment_mountains_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "mountains",
    },
    ["environment_mountains_full_scroll"] = {
      file = "assets/love_sprites/environment_mountains_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "mountains",
    },
    ["environment_mountains_parallax_far"] = {
      file = "assets/love_sprites/environment_mountains_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "mountains",
    },
    ["environment_mountains_parallax_mid"] = {
      file = "assets/love_sprites/environment_mountains_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "mountains",
    },
    ["environment_mountains_parallax_near"] = {
      file = "assets/love_sprites/environment_mountains_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "mountains",
    },
    ["environment_mountains_rail_scroll"] = {
      file = "assets/love_sprites/environment_mountains_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "mountains",
    },
    ["environment_ocean_arrival_flash"] = {
      file = "assets/love_sprites/environment_ocean_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "ocean",
    },
    ["environment_ocean_cloud_drift"] = {
      file = "assets/love_sprites/environment_ocean_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "ocean",
    },
    ["environment_ocean_danger_shake"] = {
      file = "assets/love_sprites/environment_ocean_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "ocean",
    },
    ["environment_ocean_full_scroll"] = {
      file = "assets/love_sprites/environment_ocean_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "ocean",
    },
    ["environment_ocean_parallax_far"] = {
      file = "assets/love_sprites/environment_ocean_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "ocean",
    },
    ["environment_ocean_parallax_mid"] = {
      file = "assets/love_sprites/environment_ocean_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "ocean",
    },
    ["environment_ocean_parallax_near"] = {
      file = "assets/love_sprites/environment_ocean_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "ocean",
    },
    ["environment_ocean_rail_scroll"] = {
      file = "assets/love_sprites/environment_ocean_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "ocean",
    },
    ["environment_space_arrival_flash"] = {
      file = "assets/love_sprites/environment_space_arrival_flash.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "arrival_flash",
      subject = "space",
    },
    ["environment_space_cloud_drift"] = {
      file = "assets/love_sprites/environment_space_cloud_drift.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "cloud_drift",
      subject = "space",
    },
    ["environment_space_danger_shake"] = {
      file = "assets/love_sprites/environment_space_danger_shake.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "danger_shake",
      subject = "space",
    },
    ["environment_space_full_scroll"] = {
      file = "assets/love_sprites/environment_space_full_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "full_scroll",
      subject = "space",
    },
    ["environment_space_parallax_far"] = {
      file = "assets/love_sprites/environment_space_parallax_far.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_far",
      subject = "space",
    },
    ["environment_space_parallax_mid"] = {
      file = "assets/love_sprites/environment_space_parallax_mid.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_mid",
      subject = "space",
    },
    ["environment_space_parallax_near"] = {
      file = "assets/love_sprites/environment_space_parallax_near.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "parallax_near",
      subject = "space",
    },
    ["environment_space_rail_scroll"] = {
      file = "assets/love_sprites/environment_space_rail_scroll.png",
      frameWidth = 320,
      frameHeight = 180,
      frames = 4,
      duration = 0.12,
      category = "environment",
      action = "rail_scroll",
      subject = "space",
    },
    ["fx_smoke_burst"] = {
      file = "assets/love_sprites/fx_smoke_burst.png",
      frameWidth = 64,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "fx",
      action = "burst",
      subject = "smoke",
    },
    ["fx_smoke_fade"] = {
      file = "assets/love_sprites/fx_smoke_fade.png",
      frameWidth = 64,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "fx",
      action = "fade",
      subject = "smoke",
    },
    ["fx_smoke_puff"] = {
      file = "assets/love_sprites/fx_smoke_puff.png",
      frameWidth = 64,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "fx",
      action = "puff",
      subject = "smoke",
    },
    ["hazard_boulder_active"] = {
      file = "assets/love_sprites/hazard_boulder_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "boulder",
    },
    ["hazard_boulder_broken"] = {
      file = "assets/love_sprites/hazard_boulder_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "boulder",
    },
    ["hazard_boulder_idle"] = {
      file = "assets/love_sprites/hazard_boulder_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "boulder",
    },
    ["hazard_boulder_warning"] = {
      file = "assets/love_sprites/hazard_boulder_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "boulder",
    },
    ["hazard_cactus_active"] = {
      file = "assets/love_sprites/hazard_cactus_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "cactus",
    },
    ["hazard_cactus_broken"] = {
      file = "assets/love_sprites/hazard_cactus_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "cactus",
    },
    ["hazard_cactus_idle"] = {
      file = "assets/love_sprites/hazard_cactus_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "cactus",
    },
    ["hazard_cactus_warning"] = {
      file = "assets/love_sprites/hazard_cactus_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "cactus",
    },
    ["hazard_crater_active"] = {
      file = "assets/love_sprites/hazard_crater_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "crater",
    },
    ["hazard_crater_broken"] = {
      file = "assets/love_sprites/hazard_crater_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "crater",
    },
    ["hazard_crater_idle"] = {
      file = "assets/love_sprites/hazard_crater_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "crater",
    },
    ["hazard_crater_warning"] = {
      file = "assets/love_sprites/hazard_crater_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "crater",
    },
    ["hazard_crow_active"] = {
      file = "assets/love_sprites/hazard_crow_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "crow",
    },
    ["hazard_crow_broken"] = {
      file = "assets/love_sprites/hazard_crow_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "crow",
    },
    ["hazard_crow_idle"] = {
      file = "assets/love_sprites/hazard_crow_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "crow",
    },
    ["hazard_crow_warning"] = {
      file = "assets/love_sprites/hazard_crow_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "crow",
    },
    ["hazard_ice_spike_active"] = {
      file = "assets/love_sprites/hazard_ice_spike_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "ice_spike",
    },
    ["hazard_ice_spike_broken"] = {
      file = "assets/love_sprites/hazard_ice_spike_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "ice_spike",
    },
    ["hazard_ice_spike_idle"] = {
      file = "assets/love_sprites/hazard_ice_spike_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "ice_spike",
    },
    ["hazard_ice_spike_warning"] = {
      file = "assets/love_sprites/hazard_ice_spike_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "ice_spike",
    },
    ["hazard_lantern_active"] = {
      file = "assets/love_sprites/hazard_lantern_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "lantern",
    },
    ["hazard_lantern_broken"] = {
      file = "assets/love_sprites/hazard_lantern_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "lantern",
    },
    ["hazard_lantern_idle"] = {
      file = "assets/love_sprites/hazard_lantern_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "lantern",
    },
    ["hazard_lantern_warning"] = {
      file = "assets/love_sprites/hazard_lantern_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "lantern",
    },
    ["hazard_meteor_active"] = {
      file = "assets/love_sprites/hazard_meteor_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "meteor",
    },
    ["hazard_meteor_broken"] = {
      file = "assets/love_sprites/hazard_meteor_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "meteor",
    },
    ["hazard_meteor_idle"] = {
      file = "assets/love_sprites/hazard_meteor_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "meteor",
    },
    ["hazard_meteor_warning"] = {
      file = "assets/love_sprites/hazard_meteor_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "meteor",
    },
    ["hazard_pine_rock_active"] = {
      file = "assets/love_sprites/hazard_pine_rock_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "pine_rock",
    },
    ["hazard_pine_rock_broken"] = {
      file = "assets/love_sprites/hazard_pine_rock_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "pine_rock",
    },
    ["hazard_pine_rock_idle"] = {
      file = "assets/love_sprites/hazard_pine_rock_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "pine_rock",
    },
    ["hazard_pine_rock_warning"] = {
      file = "assets/love_sprites/hazard_pine_rock_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "pine_rock",
    },
    ["hazard_snow_boulder_active"] = {
      file = "assets/love_sprites/hazard_snow_boulder_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "snow_boulder",
    },
    ["hazard_snow_boulder_broken"] = {
      file = "assets/love_sprites/hazard_snow_boulder_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "snow_boulder",
    },
    ["hazard_snow_boulder_idle"] = {
      file = "assets/love_sprites/hazard_snow_boulder_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "snow_boulder",
    },
    ["hazard_snow_boulder_warning"] = {
      file = "assets/love_sprites/hazard_snow_boulder_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "snow_boulder",
    },
    ["hazard_spiked_ball_active"] = {
      file = "assets/love_sprites/hazard_spiked_ball_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "spiked_ball",
    },
    ["hazard_spiked_ball_broken"] = {
      file = "assets/love_sprites/hazard_spiked_ball_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "spiked_ball",
    },
    ["hazard_spiked_ball_idle"] = {
      file = "assets/love_sprites/hazard_spiked_ball_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "spiked_ball",
    },
    ["hazard_spiked_ball_warning"] = {
      file = "assets/love_sprites/hazard_spiked_ball_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "spiked_ball",
    },
    ["hazard_wave_crate_active"] = {
      file = "assets/love_sprites/hazard_wave_crate_active.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "active",
      subject = "wave_crate",
    },
    ["hazard_wave_crate_broken"] = {
      file = "assets/love_sprites/hazard_wave_crate_broken.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "broken",
      subject = "wave_crate",
    },
    ["hazard_wave_crate_idle"] = {
      file = "assets/love_sprites/hazard_wave_crate_idle.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "idle",
      subject = "wave_crate",
    },
    ["hazard_wave_crate_warning"] = {
      file = "assets/love_sprites/hazard_wave_crate_warning.png",
      frameWidth = 40,
      frameHeight = 40,
      frames = 4,
      duration = 0.12,
      category = "hazard",
      action = "warning",
      subject = "wave_crate",
    },
    ["hud_heart_empty"] = {
      file = "assets/love_sprites/hud_heart_empty.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "empty",
      subject = "heart",
    },
    ["hud_heart_full"] = {
      file = "assets/love_sprites/hud_heart_full.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "full",
      subject = "heart",
    },
    ["hud_heart_gain"] = {
      file = "assets/love_sprites/hud_heart_gain.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "gain",
      subject = "heart",
    },
    ["hud_heart_lose"] = {
      file = "assets/love_sprites/hud_heart_lose.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "lose",
      subject = "heart",
    },
    ["hud_heart_pulse"] = {
      file = "assets/love_sprites/hud_heart_pulse.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "pulse",
      subject = "heart",
    },
    ["hud_meter_bone"] = {
      file = "assets/love_sprites/hud_meter_bone.png",
      frameWidth = 64,
      frameHeight = 24,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "bone",
      subject = "meter",
    },
    ["hud_meter_coin"] = {
      file = "assets/love_sprites/hud_meter_coin.png",
      frameWidth = 64,
      frameHeight = 24,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "coin",
      subject = "meter",
    },
    ["hud_meter_route_marker"] = {
      file = "assets/love_sprites/hud_meter_route_marker.png",
      frameWidth = 64,
      frameHeight = 24,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "route_marker",
      subject = "meter",
    },
    ["hud_meter_space_button"] = {
      file = "assets/love_sprites/hud_meter_space_button.png",
      frameWidth = 64,
      frameHeight = 24,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "space_button",
      subject = "meter",
    },
    ["hud_meter_whistle"] = {
      file = "assets/love_sprites/hud_meter_whistle.png",
      frameWidth = 64,
      frameHeight = 24,
      frames = 4,
      duration = 0.12,
      category = "hud",
      action = "whistle",
      subject = "meter",
    },
    ["portal_arctic_activate"] = {
      file = "assets/love_sprites/portal_arctic_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "arctic",
    },
    ["portal_arctic_closed"] = {
      file = "assets/love_sprites/portal_arctic_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "arctic",
    },
    ["portal_arctic_idle"] = {
      file = "assets/love_sprites/portal_arctic_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "arctic",
    },
    ["portal_arctic_open"] = {
      file = "assets/love_sprites/portal_arctic_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "arctic",
    },
    ["portal_city_activate"] = {
      file = "assets/love_sprites/portal_city_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "city",
    },
    ["portal_city_closed"] = {
      file = "assets/love_sprites/portal_city_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "city",
    },
    ["portal_city_idle"] = {
      file = "assets/love_sprites/portal_city_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "city",
    },
    ["portal_city_open"] = {
      file = "assets/love_sprites/portal_city_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "city",
    },
    ["portal_desert_activate"] = {
      file = "assets/love_sprites/portal_desert_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "desert",
    },
    ["portal_desert_closed"] = {
      file = "assets/love_sprites/portal_desert_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "desert",
    },
    ["portal_desert_idle"] = {
      file = "assets/love_sprites/portal_desert_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "desert",
    },
    ["portal_desert_open"] = {
      file = "assets/love_sprites/portal_desert_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "desert",
    },
    ["portal_forest_activate"] = {
      file = "assets/love_sprites/portal_forest_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "forest",
    },
    ["portal_forest_closed"] = {
      file = "assets/love_sprites/portal_forest_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "forest",
    },
    ["portal_forest_idle"] = {
      file = "assets/love_sprites/portal_forest_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "forest",
    },
    ["portal_forest_open"] = {
      file = "assets/love_sprites/portal_forest_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "forest",
    },
    ["portal_moon_activate"] = {
      file = "assets/love_sprites/portal_moon_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "moon",
    },
    ["portal_moon_closed"] = {
      file = "assets/love_sprites/portal_moon_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "moon",
    },
    ["portal_moon_idle"] = {
      file = "assets/love_sprites/portal_moon_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "moon",
    },
    ["portal_moon_open"] = {
      file = "assets/love_sprites/portal_moon_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "moon",
    },
    ["portal_mountains_activate"] = {
      file = "assets/love_sprites/portal_mountains_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "mountains",
    },
    ["portal_mountains_closed"] = {
      file = "assets/love_sprites/portal_mountains_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "mountains",
    },
    ["portal_mountains_idle"] = {
      file = "assets/love_sprites/portal_mountains_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "mountains",
    },
    ["portal_mountains_open"] = {
      file = "assets/love_sprites/portal_mountains_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "mountains",
    },
    ["portal_ocean_activate"] = {
      file = "assets/love_sprites/portal_ocean_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "ocean",
    },
    ["portal_ocean_closed"] = {
      file = "assets/love_sprites/portal_ocean_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "ocean",
    },
    ["portal_ocean_idle"] = {
      file = "assets/love_sprites/portal_ocean_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "ocean",
    },
    ["portal_ocean_open"] = {
      file = "assets/love_sprites/portal_ocean_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "ocean",
    },
    ["portal_space_activate"] = {
      file = "assets/love_sprites/portal_space_activate.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "activate",
      subject = "space",
    },
    ["portal_space_closed"] = {
      file = "assets/love_sprites/portal_space_closed.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "closed",
      subject = "space",
    },
    ["portal_space_idle"] = {
      file = "assets/love_sprites/portal_space_idle.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "idle",
      subject = "space",
    },
    ["portal_space_open"] = {
      file = "assets/love_sprites/portal_space_open.png",
      frameWidth = 56,
      frameHeight = 70,
      frames = 4,
      duration = 0.12,
      category = "portal",
      action = "open",
      subject = "space",
    },
    ["route_icon_arctic_complete"] = {
      file = "assets/love_sprites/route_icon_arctic_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "arctic",
    },
    ["route_icon_arctic_idle"] = {
      file = "assets/love_sprites/route_icon_arctic_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "arctic",
    },
    ["route_icon_arctic_selected"] = {
      file = "assets/love_sprites/route_icon_arctic_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "arctic",
    },
    ["route_icon_city_complete"] = {
      file = "assets/love_sprites/route_icon_city_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "city",
    },
    ["route_icon_city_idle"] = {
      file = "assets/love_sprites/route_icon_city_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "city",
    },
    ["route_icon_city_selected"] = {
      file = "assets/love_sprites/route_icon_city_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "city",
    },
    ["route_icon_desert_complete"] = {
      file = "assets/love_sprites/route_icon_desert_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "desert",
    },
    ["route_icon_desert_idle"] = {
      file = "assets/love_sprites/route_icon_desert_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "desert",
    },
    ["route_icon_desert_selected"] = {
      file = "assets/love_sprites/route_icon_desert_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "desert",
    },
    ["route_icon_forest_complete"] = {
      file = "assets/love_sprites/route_icon_forest_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "forest",
    },
    ["route_icon_forest_idle"] = {
      file = "assets/love_sprites/route_icon_forest_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "forest",
    },
    ["route_icon_forest_selected"] = {
      file = "assets/love_sprites/route_icon_forest_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "forest",
    },
    ["route_icon_moon_complete"] = {
      file = "assets/love_sprites/route_icon_moon_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "moon",
    },
    ["route_icon_moon_idle"] = {
      file = "assets/love_sprites/route_icon_moon_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "moon",
    },
    ["route_icon_moon_selected"] = {
      file = "assets/love_sprites/route_icon_moon_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "moon",
    },
    ["route_icon_mountains_complete"] = {
      file = "assets/love_sprites/route_icon_mountains_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "mountains",
    },
    ["route_icon_mountains_idle"] = {
      file = "assets/love_sprites/route_icon_mountains_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "mountains",
    },
    ["route_icon_mountains_selected"] = {
      file = "assets/love_sprites/route_icon_mountains_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "mountains",
    },
    ["route_icon_ocean_complete"] = {
      file = "assets/love_sprites/route_icon_ocean_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "ocean",
    },
    ["route_icon_ocean_idle"] = {
      file = "assets/love_sprites/route_icon_ocean_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "ocean",
    },
    ["route_icon_ocean_selected"] = {
      file = "assets/love_sprites/route_icon_ocean_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "ocean",
    },
    ["route_icon_space_complete"] = {
      file = "assets/love_sprites/route_icon_space_complete.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "complete",
      subject = "space",
    },
    ["route_icon_space_idle"] = {
      file = "assets/love_sprites/route_icon_space_idle.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "idle",
      subject = "space",
    },
    ["route_icon_space_selected"] = {
      file = "assets/love_sprites/route_icon_space_selected.png",
      frameWidth = 48,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "route_icon",
      action = "selected",
      subject = "space",
    },
    ["terrain_barrel_variant"] = {
      file = "assets/love_sprites/terrain_barrel_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "barrel",
    },
    ["terrain_bush_variant"] = {
      file = "assets/love_sprites/terrain_bush_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "bush",
    },
    ["terrain_cloud_variant"] = {
      file = "assets/love_sprites/terrain_cloud_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "cloud",
    },
    ["terrain_crate_variant"] = {
      file = "assets/love_sprites/terrain_crate_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "crate",
    },
    ["terrain_flower_variant"] = {
      file = "assets/love_sprites/terrain_flower_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "flower",
    },
    ["terrain_grass_variant"] = {
      file = "assets/love_sprites/terrain_grass_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "grass",
    },
    ["terrain_ice_variant"] = {
      file = "assets/love_sprites/terrain_ice_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "ice",
    },
    ["terrain_lamp_variant"] = {
      file = "assets/love_sprites/terrain_lamp_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "lamp",
    },
    ["terrain_mushroom_variant"] = {
      file = "assets/love_sprites/terrain_mushroom_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "mushroom",
    },
    ["terrain_rail_variant"] = {
      file = "assets/love_sprites/terrain_rail_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "rail",
    },
    ["terrain_rock_variant"] = {
      file = "assets/love_sprites/terrain_rock_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "rock",
    },
    ["terrain_sand_variant"] = {
      file = "assets/love_sprites/terrain_sand_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "sand",
    },
    ["terrain_sign_variant"] = {
      file = "assets/love_sprites/terrain_sign_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "sign",
    },
    ["terrain_stone_variant"] = {
      file = "assets/love_sprites/terrain_stone_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "stone",
    },
    ["terrain_water_variant"] = {
      file = "assets/love_sprites/terrain_water_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "water",
    },
    ["terrain_wood_variant"] = {
      file = "assets/love_sprites/terrain_wood_variant.png",
      frameWidth = 32,
      frameHeight = 32,
      frames = 4,
      duration = 0.12,
      category = "terrain",
      action = "variant",
      subject = "wood",
    },
  }
}
